### PR TITLE
Changes made as Google uses a new datetime format

### PR DESCRIPTION
**Pull request by Highlanderix**
My first ever contribution :)

As of late 2021 / early 2022 Google uses timestamp instead of timestampMs with a new datetime format. Changes made to parse and convert.

Name of JSON file to load changed to Records.json

### CODE REVIEW

**Comment by alabandit** [comment]
I can confirm this patch works. Thank you!

**Comment by matthieuheitz** [comment]
Thanks for the PR @Highlanderix !

**Comment by matthieuheitz** [comment]
Could one of you let me know if it makes sense to merge #8 as well?
I just haven't looked at it in years, and I currently don't have the time to dive back into the code :face_with_diagonal_mouth:

**Comment by alabandit** [comment]
I didn't use #8 so can't reply

**Pull request merged**
